//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace MoneyCounter.DataModels
{
	/// <summary>
	/// Database       : counter
	/// Data Source    : DESKTOP-RMM46MK
	/// Server Version : 12.00.2000
	/// </summary>
	public partial class CounterDB : LinqToDB.Data.DataConnection
	{
		public ITable<Credit>  Credits  { get { return this.GetTable<Credit>(); } }
		public ITable<Payment> Payments { get { return this.GetTable<Payment>(); } }

		// public CounterDB()
		// {
		// 	InitDataContext();
		// 	InitMappingSchema();
		// }

		public CounterDB(LinqToDbConnectionOptions<CounterDB> options)
			: base(options)
		{
			// InitDataContext();
			// InitMappingSchema();
		}

		// partial void InitDataContext  ();
		// partial void InitMappingSchema();
	}

	[Table(Schema="counter", Name="credit")]
	public partial class Credit
	{
		[Column("idcredit"),    PrimaryKey, Identity] public int      Idcredit   { get; set; } // int
		[Column("expiry_date"), NotNull             ] public DateTime ExpiryDate { get; set; } // date
		[Column("service"),     NotNull             ] public int      Service    { get; set; } // int
		[Column("payment"),     NotNull             ] public int      Payment    { get; set; } // int
	}

	[Table(Schema="counter", Name="payment")]
	public partial class Payment
	{
		[Column("idpayment"),         PrimaryKey,  Identity] public int      Idpayment        { get; set; } // int
		[Column("paynow_reference"),  NotNull              ] public string   PaynowReference  { get; set; } // nvarchar(100)
		[Column("payment_reference"), NotNull              ] public string   PaymentReference { get; set; } // nvarchar(50)
		[Column(),                    NotNull              ] public DateTime Date             { get; set; } // date
		[Column("description"),       NotNull              ] public string   Description      { get; set; } // nvarchar(50)
		[Column("debit"),                Nullable          ] public double?  Debit            { get; set; } // float
		[Column("credit"),               Nullable          ] public double?  Credit           { get; set; } // float
	}

	public static partial class TableExtensions
	{
		public static Credit Find(this ITable<Credit> table, int Idcredit)
		{
			return table.FirstOrDefault(t =>
				t.Idcredit == Idcredit);
		}

		public static Payment Find(this ITable<Payment> table, int Idpayment)
		{
			return table.FirstOrDefault(t =>
				t.Idpayment == Idpayment);
		}
	}
}

#pragma warning restore 1591
